version : '3'

services:

  iakimv2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      liferay:

  iakimv1:
    image: iakim/liferay-docker:latest
    ports:
      - "8080:8080"
      - "9990:9990"
    networks:
      liferay:

networks:
  liferay:
    driver: bridge
